//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.OnlineForms;
using CMS.OnlineForms.Types;

[assembly: RegisterBizForm(Form_2023_02_03_18_1Item.CLASS_NAME, typeof(Form_2023_02_03_18_1Item))]

namespace CMS.OnlineForms.Types
{
	/// <summary>
	/// Represents a content item of type Form_2023_02_03_18_1Item.
	/// </summary>
	public partial class Form_2023_02_03_18_1Item : BizFormItem
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "BizForm.Form_2023_02_03_18_1";


		/// <summary>
		/// The instance of the class that provides extended API for working with Form_2023_02_03_18_1Item fields.
		/// </summary>
		private readonly Form_2023_02_03_18_1ItemFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// Gets an object that provides extended API for working with Form_2023_02_03_18_1Item fields.
		/// </summary>
		[RegisterProperty]
		public Form_2023_02_03_18_1ItemFields Fields
		{
			get => mFields;
		}


		/// <summary>
		/// Provides extended API for working with Form_2023_02_03_18_1Item fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class Form_2023_02_03_18_1ItemFields : AbstractHierarchicalObject<Form_2023_02_03_18_1ItemFields>
		{
			/// <summary>
			/// The content item of type Form_2023_02_03_18_1Item that is a target of the extended API.
			/// </summary>
			private readonly Form_2023_02_03_18_1Item mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="Form_2023_02_03_18_1ItemFields" /> class with the specified content item of type Form_2023_02_03_18_1Item.
			/// </summary>
			/// <param name="instance">The content item of type Form_2023_02_03_18_1Item that is a target of the extended API.</param>
			public Form_2023_02_03_18_1ItemFields(Form_2023_02_03_18_1Item instance)
			{
				mInstance = instance;
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="Form_2023_02_03_18_1Item" /> class.
		/// </summary>
		public Form_2023_02_03_18_1Item() : base(CLASS_NAME)
		{
			mFields = new Form_2023_02_03_18_1ItemFields(this);
		}

		#endregion
	}
}