//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace TrainingGuides
{
	/// <summary>
	/// Defines a contract for content types with the <see cref="IProductSchema"/> reusable schema assigned.
	/// </summary>
	public interface IProductSchema
	{
		/// <summary>
		/// Code name of the reusable field schema.
		/// </summary>
		public const string REUSABLE_FIELD_SCHEMA_NAME = "ProductSchema";


		/// <summary>
		/// ProductSchemaName.
		/// </summary>
		public string ProductSchemaName { get; set; }


		/// <summary>
		/// ProductSchemaImages.
		/// </summary>
		public IEnumerable<ProductImage> ProductSchemaImages { get; set; }


		/// <summary>
		/// ProductSchemaDescription.
		/// </summary>
		public string ProductSchemaDescription { get; set; }
	}
}