//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS.ContentEngine;

namespace DancingGoat.Models
{
	/// <summary>
	/// Defines a contract for content types with the <see cref="IProductFields"/> reusable schema assigned.
	/// </summary>
	public interface IProductFields
	{
		/// <summary>
		/// Code name of the reusable field schema.
		/// </summary>
		public const string REUSABLE_FIELD_SCHEMA_NAME = "ProductFields";


		/// <summary>
		/// ProductFieldName.
		/// </summary>
		public string ProductFieldName { get; set; }


		/// <summary>
		/// ProductFieldDescription.
		/// </summary>
		public string ProductFieldDescription { get; set; }


		/// <summary>
		/// ProductFieldImage.
		/// </summary>
		public IEnumerable<Image> ProductFieldImage { get; set; }


		/// <summary>
		/// ProductFieldPrice.
		/// </summary>
		public decimal ProductFieldPrice { get; set; }


		/// <summary>
		/// ProductFieldTags.
		/// </summary>
		public IEnumerable<TagReference> ProductFieldTags { get; set; }


		/// <summary>
		/// ProductFieldCategory.
		/// </summary>
		public IEnumerable<TagReference> ProductFieldCategory { get; set; }
	}
}