//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.OnlineForms;
using CMS.OnlineForms.Types;

[assembly: RegisterBizForm(ContactItem.CLASS_NAME, typeof(ContactItem))]

namespace CMS.OnlineForms.Types
{
	/// <summary>
	/// Represents a content item of type ContactItem.
	/// </summary>
	public partial class ContactItem : BizFormItem
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "BizForm.Contact";


		/// <summary>
		/// The instance of the class that provides extended API for working with ContactItem fields.
		/// </summary>
		private readonly ContactItemFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// FirstName.
		/// </summary>
		[DatabaseField]
		public string FirstName
		{
			get => ValidationHelper.GetString(GetValue(nameof(FirstName)), @"");
			set => SetValue(nameof(FirstName), value);
		}


		/// <summary>
		/// LastName.
		/// </summary>
		[DatabaseField]
		public string LastName
		{
			get => ValidationHelper.GetString(GetValue(nameof(LastName)), @"");
			set => SetValue(nameof(LastName), value);
		}


		/// <summary>
		/// Email.
		/// </summary>
		[DatabaseField]
		public string Email
		{
			get => ValidationHelper.GetString(GetValue(nameof(Email)), @"");
			set => SetValue(nameof(Email), value);
		}


		/// <summary>
		/// Message.
		/// </summary>
		[DatabaseField]
		public string Message
		{
			get => ValidationHelper.GetString(GetValue(nameof(Message)), @"");
			set => SetValue(nameof(Message), value);
		}


		/// <summary>
		/// Gets an object that provides extended API for working with ContactItem fields.
		/// </summary>
		[RegisterProperty]
		public ContactItemFields Fields
		{
			get => mFields;
		}


		/// <summary>
		/// Provides extended API for working with ContactItem fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class ContactItemFields : AbstractHierarchicalObject<ContactItemFields>
		{
			/// <summary>
			/// The content item of type ContactItem that is a target of the extended API.
			/// </summary>
			private readonly ContactItem mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="ContactItemFields" /> class with the specified content item of type ContactItem.
			/// </summary>
			/// <param name="instance">The content item of type ContactItem that is a target of the extended API.</param>
			public ContactItemFields(ContactItem instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// FirstName.
			/// </summary>
			public string FirstName
			{
				get => mInstance.FirstName;
				set => mInstance.FirstName = value;
			}


			/// <summary>
			/// LastName.
			/// </summary>
			public string LastName
			{
				get => mInstance.LastName;
				set => mInstance.LastName = value;
			}


			/// <summary>
			/// Email.
			/// </summary>
			public string Email
			{
				get => mInstance.Email;
				set => mInstance.Email = value;
			}


			/// <summary>
			/// Message.
			/// </summary>
			public string Message
			{
				get => mInstance.Message;
				set => mInstance.Message = value;
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="ContactItem" /> class.
		/// </summary>
		public ContactItem() : base(CLASS_NAME)
		{
			mFields = new ContactItemFields(this);
		}

		#endregion
	}
}