//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.OnlineForms;
using CMS.OnlineForms.Types;

[assembly: RegisterBizForm(TestConsentFormItem.CLASS_NAME, typeof(TestConsentFormItem))]

namespace CMS.OnlineForms.Types
{
	/// <summary>
	/// Represents a content item of type TestConsentFormItem.
	/// </summary>
	public partial class TestConsentFormItem : BizFormItem
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "BizForm.TestConsentForm";


		/// <summary>
		/// The instance of the class that provides extended API for working with TestConsentFormItem fields.
		/// </summary>
		private readonly TestConsentFormItemFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// ConsentAgreement.
		/// </summary>
		[DatabaseField]
		public Guid ConsentAgreement
		{
			get => ValidationHelper.GetGuid(GetValue(nameof(ConsentAgreement)), Guid.Empty);
			set => SetValue(nameof(ConsentAgreement), value);
		}


		/// <summary>
		/// Gets an object that provides extended API for working with TestConsentFormItem fields.
		/// </summary>
		[RegisterProperty]
		public TestConsentFormItemFields Fields
		{
			get => mFields;
		}


		/// <summary>
		/// Provides extended API for working with TestConsentFormItem fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class TestConsentFormItemFields : AbstractHierarchicalObject<TestConsentFormItemFields>
		{
			/// <summary>
			/// The content item of type TestConsentFormItem that is a target of the extended API.
			/// </summary>
			private readonly TestConsentFormItem mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="TestConsentFormItemFields" /> class with the specified content item of type TestConsentFormItem.
			/// </summary>
			/// <param name="instance">The content item of type TestConsentFormItem that is a target of the extended API.</param>
			public TestConsentFormItemFields(TestConsentFormItem instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// ConsentAgreement.
			/// </summary>
			public Guid ConsentAgreement
			{
				get => mInstance.ConsentAgreement;
				set => mInstance.ConsentAgreement = value;
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="TestConsentFormItem" /> class.
		/// </summary>
		public TestConsentFormItem() : base(CLASS_NAME)
		{
			mFields = new TestConsentFormItemFields(this);
		}

		#endregion
	}
}