//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS.ContentEngine;

namespace TrainingGuides
{
	/// <summary>
	/// Represents a content item of type <see cref="DogCollarVariant"/>.
	/// </summary>
	[RegisterContentTypeMapping(CONTENT_TYPE_NAME)]
	public partial class DogCollarVariant : IContentItemFieldsSource, IProductSchema, IColorPatternSchema, IProductSkuSchema, IProductShippingSchema, ISizeSchema, IProductPriceSchema, IProductVariantSchema
	{
		/// <summary>
		/// Code name of the content type.
		/// </summary>
		public const string CONTENT_TYPE_NAME = "TrainingGuides.DogCollarVariant";


		/// <summary>
		/// Represents system properties for a content item.
		/// </summary>
		[SystemField]
		public ContentItemFields SystemFields { get; set; }


		/// <summary>
		/// ProductSchemaName.
		/// </summary>
		public string ProductSchemaName { get; set; }


		/// <summary>
		/// ProductSchemaImages.
		/// </summary>
		public IEnumerable<ProductImage> ProductSchemaImages { get; set; }


		/// <summary>
		/// ProductSchemaDescription.
		/// </summary>
		public string ProductSchemaDescription { get; set; }


		/// <summary>
		/// ColorPattern.
		/// </summary>
		public IEnumerable<TagReference> ColorPattern { get; set; }


		/// <summary>
		/// ProductSkuSchemaSkuCode.
		/// </summary>
		public string ProductSkuSchemaSkuCode { get; set; }


		/// <summary>
		/// ProductShippingSchemaShippingType.
		/// </summary>
		public string ProductShippingSchemaShippingType { get; set; }


		/// <summary>
		/// ProductShippingSchemaShippingWeight.
		/// </summary>
		public decimal ProductShippingSchemaShippingWeight { get; set; }


		/// <summary>
		/// ProductShippingSchemaWeightUnit.
		/// </summary>
		public string ProductShippingSchemaWeightUnit { get; set; }


		/// <summary>
		/// SizeSchemaSize.
		/// </summary>
		public IEnumerable<TagReference> SizeSchemaSize { get; set; }


		/// <summary>
		/// ProductPriceSchemaPrice.
		/// </summary>
		public decimal ProductPriceSchemaPrice { get; set; }


		/// <summary>
		/// ProductPriceSchemaDiscountCategory.
		/// </summary>
		public IEnumerable<TagReference> ProductPriceSchemaDiscountCategory { get; set; }


		/// <summary>
		/// ProductVariantSchemaCodeName.
		/// </summary>
		public string ProductVariantSchemaCodeName { get; set; }
	}
}