//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS.ContentEngine;

namespace TrainingGuides
{
	/// <summary>
	/// Represents a content item of type <see cref="Service"/>.
	/// </summary>
	[RegisterContentTypeMapping(CONTENT_TYPE_NAME)]
	public partial class Service : IContentItemFieldsSource
	{
		/// <summary>
		/// Code name of the content type.
		/// </summary>
		public const string CONTENT_TYPE_NAME = "TrainingGuides.Service";


		/// <summary>
		/// Represents system properties for a content item.
		/// </summary>
		[SystemField]
		public ContentItemFields SystemFields { get; set; }


		/// <summary>
		/// ServiceName.
		/// </summary>
		public string ServiceName { get; set; }


		/// <summary>
		/// ServiceShortDescription.
		/// </summary>
		public string ServiceShortDescription { get; set; }


		/// <summary>
		/// ServiceMedia.
		/// </summary>
		public IEnumerable<Asset> ServiceMedia { get; set; }


		/// <summary>
		/// ServiceDescription.
		/// </summary>
		public string ServiceDescription { get; set; }


		/// <summary>
		/// ServiceBenefits.
		/// </summary>
		public IEnumerable<Benefit> ServiceBenefits { get; set; }


		/// <summary>
		/// ServiceFeatures.
		/// </summary>
		public IEnumerable<ServiceFeature> ServiceFeatures { get; set; }


		/// <summary>
		/// ServicePrice.
		/// </summary>
		public decimal ServicePrice { get; set; }
	}
}