//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kentico.Xperience.Mjml.StarterKit.Rcl.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal partial class MjmlStarterKitResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MjmlStarterKitResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kentico.Xperience.Mjml.StarterKit.Rcl.Resources.MjmlStarterKitResources", typeof(MjmlStarterKitResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Button.
        /// </summary>
        internal static string ButtonType_Button {
            get {
                return ResourceManager.GetString("ButtonType.Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link.
        /// </summary>
        internal static string ButtonType_Link {
            get {
                return ResourceManager.GetString("ButtonType.Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the button alignment.
        /// </summary>
        internal static string ButtonWidget_Alignment_ExplanationText {
            get {
                return ResourceManager.GetString("ButtonWidget.Alignment.ExplanationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alignment.
        /// </summary>
        internal static string ButtonWidget_Alignment_Label {
            get {
                return ResourceManager.GetString("ButtonWidget.Alignment.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the button type.
        /// </summary>
        internal static string ButtonWidget_ButtonType_ExplanationText {
            get {
                return ResourceManager.GetString("ButtonWidget.ButtonType.ExplanationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ButtonType.
        /// </summary>
        internal static string ButtonWidget_ButtonType_Label {
            get {
                return ResourceManager.GetString("ButtonWidget.ButtonType.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays a button with a link to a web page..
        /// </summary>
        internal static string ButtonWidget_Description {
            get {
                return ResourceManager.GetString("ButtonWidget.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Button.
        /// </summary>
        internal static string ButtonWidget_Name {
            get {
                return ResourceManager.GetString("ButtonWidget.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the button text.
        /// </summary>
        internal static string ButtonWidget_Text_ExplanationText {
            get {
                return ResourceManager.GetString("ButtonWidget.Text.ExplanationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Button Text.
        /// </summary>
        internal static string ButtonWidget_Text_Label {
            get {
                return ResourceManager.GetString("ButtonWidget.Text.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the button link URL. Allowed formats: absolute (starting with protocol), rooted (starting with /), or virtual (starting with ~).
        /// </summary>
        internal static string ButtonWidget_Url_ExplanationText {
            get {
                return ResourceManager.GetString("ButtonWidget.Url.ExplanationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL.
        /// </summary>
        internal static string ButtonWidget_Url_Label {
            get {
                return ResourceManager.GetString("ButtonWidget.Url.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set the color of divider by name or hex code (ie. blue or #fed).
        /// </summary>
        internal static string DividerWidget_BorderColor_ExplanationText {
            get {
                return ResourceManager.GetString("DividerWidget.BorderColor.ExplanationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Border color.
        /// </summary>
        internal static string DividerWidget_BorderColor_Label {
            get {
                return ResourceManager.GetString("DividerWidget.BorderColor.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can specify the border style here (dashed/dotted/solid)..
        /// </summary>
        internal static string DividerWidget_BorderStyle_ExplanationText {
            get {
                return ResourceManager.GetString("DividerWidget.BorderStyle.ExplanationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Border color.
        /// </summary>
        internal static string DividerWidget_BorderStyle_Label {
            get {
                return ResourceManager.GetString("DividerWidget.BorderStyle.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set the border of divider in pixels.
        /// </summary>
        internal static string DividerWidget_BorderWidth_ExplanationText {
            get {
                return ResourceManager.GetString("DividerWidget.BorderWidth.ExplanationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Border width.
        /// </summary>
        internal static string DividerWidget_BorderWidth_Label {
            get {
                return ResourceManager.GetString("DividerWidget.BorderWidth.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays a divider..
        /// </summary>
        internal static string DividerWidget_Description {
            get {
                return ResourceManager.GetString("DividerWidget.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Divider.
        /// </summary>
        internal static string DividerWidget_Name {
            get {
                return ResourceManager.GetString("DividerWidget.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Width Email Section.
        /// </summary>
        internal static string FullWidthEmailSection_Name {
            get {
                return ResourceManager.GetString("FullWidthEmailSection.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center.
        /// </summary>
        internal static string HorizontalAlignment_Center {
            get {
                return ResourceManager.GetString("HorizontalAlignment.Center", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left.
        /// </summary>
        internal static string HorizontalAlignment_Left {
            get {
                return ResourceManager.GetString("HorizontalAlignment.Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right.
        /// </summary>
        internal static string HorizontalAlignment_Right {
            get {
                return ResourceManager.GetString("HorizontalAlignment.Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select image alignment..
        /// </summary>
        internal static string ImageWidget_Alignment_ExplanationText {
            get {
                return ResourceManager.GetString("ImageWidget.Alignment.ExplanationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alignment.
        /// </summary>
        internal static string ImageWidget_Alignment_Label {
            get {
                return ResourceManager.GetString("ImageWidget.Alignment.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays an image..
        /// </summary>
        internal static string ImageWidget_Description {
            get {
                return ResourceManager.GetString("ImageWidget.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image from the content hub..
        /// </summary>
        internal static string ImageWidget_Image_ExplanationText {
            get {
                return ResourceManager.GetString("ImageWidget.Image.ExplanationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        internal static string ImageWidget_Image_Label {
            get {
                return ResourceManager.GetString("ImageWidget.Image.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        internal static string ImageWidget_Name {
            get {
                return ResourceManager.GetString("ImageWidget.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required width of the image..
        /// </summary>
        internal static string ImageWidget_Width_ExplanationText {
            get {
                return ResourceManager.GetString("ImageWidget.Width.ExplanationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        internal static string ImageWidget_Width_Label {
            get {
                return ResourceManager.GetString("ImageWidget.Width.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays a product with an image, title, and text content from a selected web page..
        /// </summary>
        internal static string ProductWidget_Description {
            get {
                return ResourceManager.GetString("ProductWidget.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        internal static string ProductWidget_Name {
            get {
                return ResourceManager.GetString("ProductWidget.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a web page..
        /// </summary>
        internal static string ProductWidget_Page_ExplanationText {
            get {
                return ResourceManager.GetString("ProductWidget.Page.ExplanationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page.
        /// </summary>
        internal static string ProductWidget_Page_Label {
            get {
                return ResourceManager.GetString("ProductWidget.Page.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set the text of the button which links the original web page item..
        /// </summary>
        internal static string ProductWidget_ReadMoreButton_ExplanationText {
            get {
                return ResourceManager.GetString("ProductWidget.ReadMoreButton.ExplanationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to Web Page Button Text.
        /// </summary>
        internal static string ProductWidget_ReadMoreButton_Label {
            get {
                return ResourceManager.GetString("ProductWidget.ReadMoreButton.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays text content in your email..
        /// </summary>
        internal static string TextWidget_Description {
            get {
                return ResourceManager.GetString("TextWidget.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        internal static string TextWidget_Name {
            get {
                return ResourceManager.GetString("TextWidget.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two Columns Email Section.
        /// </summary>
        internal static string TwoColumnsEmailSection_Name {
            get {
                return ResourceManager.GetString("TwoColumnsEmailSection.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSS class for this block..
        /// </summary>
        internal static string WidgetPropertiesBase_CssClass_ExplanationText {
            get {
                return ResourceManager.GetString("WidgetPropertiesBase.CssClass.ExplanationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSS class.
        /// </summary>
        internal static string WidgetPropertiesBase_CssClass_Label {
            get {
                return ResourceManager.GetString("WidgetPropertiesBase.CssClass.Label", resourceCulture);
            }
        }
    }
}
