//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS.ContentEngine;

namespace TrainingGuides
{
	/// <summary>
	/// Represents a content item of type <see cref="GeneralArticle"/>.
	/// </summary>
	[RegisterContentTypeMapping(CONTENT_TYPE_NAME)]
	public partial class GeneralArticle : IContentItemFieldsSource, IArticleSchema
	{
		/// <summary>
		/// Code name of the content type.
		/// </summary>
		public const string CONTENT_TYPE_NAME = "TrainingGuides.GeneralArticle";


		/// <summary>
		/// Represents system properties for a content item.
		/// </summary>
		[SystemField]
		public ContentItemFields SystemFields { get; set; }


		/// <summary>
		/// ArticleSchemaTitle.
		/// </summary>
		public string ArticleSchemaTitle { get; set; }


		/// <summary>
		/// ArticleSchemaTeaser.
		/// </summary>
		public IEnumerable<Asset> ArticleSchemaTeaser { get; set; }


		/// <summary>
		/// ArticleSchemaSummary.
		/// </summary>
		public string ArticleSchemaSummary { get; set; }


		/// <summary>
		/// ArticleSchemaText.
		/// </summary>
		public string ArticleSchemaText { get; set; }


		/// <summary>
		/// ArticleSchemaRelatedArticles.
		/// </summary>
		public IEnumerable<Article> ArticleSchemaRelatedArticles { get; set; }


		/// <summary>
		/// ArticleSchemaCategory.
		/// </summary>
		public IEnumerable<TagReference> ArticleSchemaCategory { get; set; }
	}
}