//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine;
using CMS.DocumentEngine.Types.KBank;

[assembly: RegisterDocumentType(PlainPage.CLASS_NAME, typeof(PlainPage))]

namespace CMS.DocumentEngine.Types.KBank
{
	/// <summary>
	/// Represents a content item of type PlainPage.
	/// </summary>
	public partial class PlainPage : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "KBank.PlainPage";


		/// <summary>
		/// The instance of the class that provides extended API for working with PlainPage fields.
		/// </summary>
		private readonly PlainPageFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// PlainPageID.
		/// </summary>
		[DatabaseIDField]
		public int PlainPageID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("PlainPageID"), 0);
			}
			set
			{
				SetValue("PlainPageID", value);
			}
		}


		/// <summary>
		/// PlainPageNotes.
		/// </summary>
		[DatabaseField]
		public string PlainPageNotes
		{
			get
			{
				return ValidationHelper.GetString(GetValue("PlainPageNotes"), @"");
			}
			set
			{
				SetValue("PlainPageNotes", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with PlainPage fields.
		/// </summary>
		[RegisterProperty]
		public PlainPageFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with PlainPage fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class PlainPageFields : AbstractHierarchicalObject<PlainPageFields>
		{
			/// <summary>
			/// The content item of type PlainPage that is a target of the extended API.
			/// </summary>
			private readonly PlainPage mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="PlainPageFields" /> class with the specified content item of type PlainPage.
			/// </summary>
			/// <param name="instance">The content item of type PlainPage that is a target of the extended API.</param>
			public PlainPageFields(PlainPage instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// PlainPageID.
			/// </summary>
			public int ID
			{
				get
				{
					return mInstance.PlainPageID;
				}
				set
				{
					mInstance.PlainPageID = value;
				}
			}


			/// <summary>
			/// PlainPageNotes.
			/// </summary>
			public string Notes
			{
				get
				{
					return mInstance.PlainPageNotes;
				}
				set
				{
					mInstance.PlainPageNotes = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="PlainPage" /> class.
		/// </summary>
		public PlainPage() : base(CLASS_NAME)
		{
			mFields = new PlainPageFields(this);
		}

		#endregion
	}
}