//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS.ContentEngine;

namespace TrainingGuides
{
	/// <summary>
	/// Represents a content item of type <see cref="Asset"/>.
	/// </summary>
	public partial class Asset : IContentItemFieldsSource
	{
		/// <summary>
		/// Code name of the content type.
		/// </summary>
		public const string CONTENT_TYPE_NAME = "TrainingGuides.Asset";


		/// <summary>
		/// Represents system properties for a content item.
		/// </summary>
		public ContentItemFields SystemFields { get; set; }


		/// <summary>
		/// AssetDescription.
		/// </summary>
		public string AssetDescription { get; set; }


		/// <summary>
		/// AssetAltText.
		/// </summary>
		public string AssetAltText { get; set; }


		/// <summary>
		/// AssetUseInternalOnly.
		/// </summary>
		public bool AssetUseInternalOnly { get; set; }


		/// <summary>
		/// AssetFile.
		/// </summary>
		public ContentItemAsset AssetFile { get; set; }
	}
}