//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS.ContentEngine;

namespace TrainingGuides
{
	/// <summary>
	/// Represents a content item of type <see cref="DogCollar"/>.
	/// </summary>
	[RegisterContentTypeMapping(CONTENT_TYPE_NAME)]
	public partial class DogCollar : IContentItemFieldsSource, IProductSchema, IMaterialSchema, IProductParentSchema
	{
		/// <summary>
		/// Code name of the content type.
		/// </summary>
		public const string CONTENT_TYPE_NAME = "TrainingGuides.DogCollar";


		/// <summary>
		/// Represents system properties for a content item.
		/// </summary>
		[SystemField]
		public ContentItemFields SystemFields { get; set; }


		/// <summary>
		/// ProductSchemaName.
		/// </summary>
		public string ProductSchemaName { get; set; }


		/// <summary>
		/// ProductSchemaImages.
		/// </summary>
		public IEnumerable<ProductImage> ProductSchemaImages { get; set; }


		/// <summary>
		/// ProductSchemaDescription.
		/// </summary>
		public string ProductSchemaDescription { get; set; }


		/// <summary>
		/// MaterialSchemaMaterial.
		/// </summary>
		public IEnumerable<TagReference> MaterialSchemaMaterial { get; set; }


		/// <summary>
		/// ProductParentSchemaVariants.
		/// </summary>
		public IEnumerable<IProductVariantSchema> ProductParentSchemaVariants { get; set; }
	}
}