//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS.ContentEngine;

namespace TrainingGuides
{
	/// <summary>
	/// Represents a content item of type <see cref="GalleryImage"/>.
	/// </summary>
	[RegisterContentTypeMapping(CONTENT_TYPE_NAME)]
	public partial class GalleryImage : IContentItemFieldsSource
	{
		/// <summary>
		/// Code name of the content type.
		/// </summary>
		public const string CONTENT_TYPE_NAME = "TrainingGuides.GalleryImage";


		/// <summary>
		/// Represents system properties for a content item.
		/// </summary>
		[SystemField]
		public ContentItemFields SystemFields { get; set; }


		/// <summary>
		/// GalleryImageAsset.
		/// </summary>
		public ContentItemAsset GalleryImageAsset { get; set; }


		/// <summary>
		/// GalleryImageDescription.
		/// </summary>
		public string GalleryImageDescription { get; set; }


		/// <summary>
		/// GalleryImageCategory.
		/// </summary>
		public IEnumerable<TagReference> GalleryImageCategory { get; set; }
	}
}