//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS.ContentEngine;

namespace KBank
{
	/// <summary>
	/// Represents a content item of type <see cref="LandingContent"/>.
	/// </summary>
	public partial class LandingContent
	{
		/// <summary>
		/// Code name of the content type.
		/// </summary>
		public const string CONTENT_TYPE_NAME = "KBank.LandingContent";


		/// <summary>
		/// Represents system properties for a content item.
		/// </summary>
		public ContentItemFields SystemFields { get; set; }


		/// <summary>
		/// Message.
		/// </summary>
		public string Message { get; set; }


		/// <summary>
		/// Text.
		/// </summary>
		public string Text { get; set; }
	}
}