//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS.ContentEngine;

namespace TrainingGuides
{
	/// <summary>
	/// Represents a content item of type <see cref="ServiceFeature"/>.
	/// </summary>
	[RegisterContentTypeMapping(CONTENT_TYPE_NAME)]
	public partial class ServiceFeature : IContentItemFieldsSource
	{
		/// <summary>
		/// Code name of the content type.
		/// </summary>
		public const string CONTENT_TYPE_NAME = "TrainingGuides.ServiceFeature";


		/// <summary>
		/// Represents system properties for a content item.
		/// </summary>
		[SystemField]
		public ContentItemFields SystemFields { get; set; }


		/// <summary>
		/// ServiceFeatureLabel.
		/// </summary>
		public string ServiceFeatureLabel { get; set; }


		/// <summary>
		/// ServiceFeatureKey.
		/// </summary>
		public string ServiceFeatureKey { get; set; }


		/// <summary>
		/// ServiceFeatureValueType.
		/// </summary>
		public string ServiceFeatureValueType { get; set; }


		/// <summary>
		/// ServiceFeatureValue.
		/// </summary>
		public string ServiceFeatureValue { get; set; }


		/// <summary>
		/// ServiceFeaturePrice.
		/// </summary>
		public decimal ServiceFeaturePrice { get; set; }


		/// <summary>
		/// ServiceFeatureIncluded.
		/// </summary>
		public bool ServiceFeatureIncluded { get; set; }


		/// <summary>
		/// ServiceFeatureShowInComparator.
		/// </summary>
		public string ServiceFeatureShowInComparator { get; set; }
	}
}