//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine;
using CMS.DocumentEngine.Types.KBank;

[assembly: RegisterDocumentType(DownloadPage.CLASS_NAME, typeof(DownloadPage))]

namespace CMS.DocumentEngine.Types.KBank
{
	/// <summary>
	/// Represents a content item of type DownloadPage.
	/// </summary>
	public partial class DownloadPage : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "KBank.DownloadPage";


		/// <summary>
		/// The instance of the class that provides extended API for working with DownloadPage fields.
		/// </summary>
		private readonly DownloadPageFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// DownloadPageID.
		/// </summary>
		[DatabaseIDField]
		public int DownloadPageID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("DownloadPageID"), 0);
			}
			set
			{
				SetValue("DownloadPageID", value);
			}
		}


		/// <summary>
		/// Heading.
		/// </summary>
		[DatabaseField]
		public string Heading
		{
			get
			{
				return ValidationHelper.GetString(GetValue("Heading"), @"");
			}
			set
			{
				SetValue("Heading", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with DownloadPage fields.
		/// </summary>
		[RegisterProperty]
		public DownloadPageFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with DownloadPage fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class DownloadPageFields : AbstractHierarchicalObject<DownloadPageFields>
		{
			/// <summary>
			/// The content item of type DownloadPage that is a target of the extended API.
			/// </summary>
			private readonly DownloadPage mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="DownloadPageFields" /> class with the specified content item of type DownloadPage.
			/// </summary>
			/// <param name="instance">The content item of type DownloadPage that is a target of the extended API.</param>
			public DownloadPageFields(DownloadPage instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// DownloadPageID.
			/// </summary>
			public int ID
			{
				get
				{
					return mInstance.DownloadPageID;
				}
				set
				{
					mInstance.DownloadPageID = value;
				}
			}


			/// <summary>
			/// Heading.
			/// </summary>
			public string Heading
			{
				get
				{
					return mInstance.Heading;
				}
				set
				{
					mInstance.Heading = value;
				}
			}


			/// <summary>
			/// Assets.
			/// </summary>
			public IEnumerable<TreeNode> Assets
			{
				get
				{
					return (mInstance.LinkedContentItems["Assets"]);
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="DownloadPage" /> class.
		/// </summary>
		public DownloadPage() : base(CLASS_NAME)
		{
			mFields = new DownloadPageFields(this);
		}

		#endregion
	}
}